apiVersion: v1
kind: Pod
metadata:
  name: busybox-lcy
  labels:
    purpose: ping-lcy
spec:
  containers:
  - name: busybox
    image: lzxdomain.com/devops/busybox:v1
    args:
    - sleep
    - "3600"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

